/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authedRouteRouteImport } from './routes/(authed)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authedProfileRouteImport } from './routes/(authed)/profile'
import { Route as authedLeaderboardRouteImport } from './routes/(authed)/leaderboard'
import { Route as authedKirtanRouteImport } from './routes/(authed)/kirtan'
import { Route as authedFeedRouteImport } from './routes/(authed)/feed'
import { Route as authedAccountRouteImport } from './routes/(authed)/account'
import { Route as authedUsernameRouteImport } from './routes/(authed)/$username'
import { Route as ApiLeaderboardSubscribeRouteImport } from './routes/api/leaderboard/subscribe'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authedEchoEchoIdRouteImport } from './routes/(authed)/echo.$echoId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authedRouteRoute = authedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authedProfileRoute = authedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedLeaderboardRoute = authedLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedKirtanRoute = authedKirtanRouteImport.update({
  id: '/kirtan',
  path: '/kirtan',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedFeedRoute = authedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedAccountRoute = authedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedUsernameRoute = authedUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => authedRouteRoute,
} as any)
const ApiLeaderboardSubscribeRoute = ApiLeaderboardSubscribeRouteImport.update({
  id: '/api/leaderboard/subscribe',
  path: '/api/leaderboard/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authedEchoEchoIdRoute = authedEchoEchoIdRouteImport.update({
  id: '/echo/$echoId',
  path: '/echo/$echoId',
  getParentRoute: () => authedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$username': typeof authedUsernameRoute
  '/account': typeof authedAccountRoute
  '/feed': typeof authedFeedRoute
  '/kirtan': typeof authedKirtanRoute
  '/leaderboard': typeof authedLeaderboardRoute
  '/profile': typeof authedProfileRoute
  '/echo/$echoId': typeof authedEchoEchoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/leaderboard/subscribe': typeof ApiLeaderboardSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$username': typeof authedUsernameRoute
  '/account': typeof authedAccountRoute
  '/feed': typeof authedFeedRoute
  '/kirtan': typeof authedKirtanRoute
  '/leaderboard': typeof authedLeaderboardRoute
  '/profile': typeof authedProfileRoute
  '/echo/$echoId': typeof authedEchoEchoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/leaderboard/subscribe': typeof ApiLeaderboardSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authed)': typeof authedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/(authed)/$username': typeof authedUsernameRoute
  '/(authed)/account': typeof authedAccountRoute
  '/(authed)/feed': typeof authedFeedRoute
  '/(authed)/kirtan': typeof authedKirtanRoute
  '/(authed)/leaderboard': typeof authedLeaderboardRoute
  '/(authed)/profile': typeof authedProfileRoute
  '/(authed)/echo/$echoId': typeof authedEchoEchoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/leaderboard/subscribe': typeof ApiLeaderboardSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/$username'
    | '/account'
    | '/feed'
    | '/kirtan'
    | '/leaderboard'
    | '/profile'
    | '/echo/$echoId'
    | '/api/auth/$'
    | '/api/leaderboard/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/$username'
    | '/account'
    | '/feed'
    | '/kirtan'
    | '/leaderboard'
    | '/profile'
    | '/echo/$echoId'
    | '/api/auth/$'
    | '/api/leaderboard/subscribe'
  id:
    | '__root__'
    | '/'
    | '/(authed)'
    | '/login'
    | '/signup'
    | '/(authed)/$username'
    | '/(authed)/account'
    | '/(authed)/feed'
    | '/(authed)/kirtan'
    | '/(authed)/leaderboard'
    | '/(authed)/profile'
    | '/(authed)/echo/$echoId'
    | '/api/auth/$'
    | '/api/leaderboard/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authedRouteRoute: typeof authedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLeaderboardSubscribeRoute: typeof ApiLeaderboardSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)': {
      id: '/(authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/profile': {
      id: '/(authed)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authedProfileRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/leaderboard': {
      id: '/(authed)/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof authedLeaderboardRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/kirtan': {
      id: '/(authed)/kirtan'
      path: '/kirtan'
      fullPath: '/kirtan'
      preLoaderRoute: typeof authedKirtanRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/feed': {
      id: '/(authed)/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof authedFeedRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/account': {
      id: '/(authed)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof authedAccountRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/$username': {
      id: '/(authed)/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof authedUsernameRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/api/leaderboard/subscribe': {
      id: '/api/leaderboard/subscribe'
      path: '/api/leaderboard/subscribe'
      fullPath: '/api/leaderboard/subscribe'
      preLoaderRoute: typeof ApiLeaderboardSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/echo/$echoId': {
      id: '/(authed)/echo/$echoId'
      path: '/echo/$echoId'
      fullPath: '/echo/$echoId'
      preLoaderRoute: typeof authedEchoEchoIdRouteImport
      parentRoute: typeof authedRouteRoute
    }
  }
}

interface authedRouteRouteChildren {
  authedUsernameRoute: typeof authedUsernameRoute
  authedAccountRoute: typeof authedAccountRoute
  authedFeedRoute: typeof authedFeedRoute
  authedKirtanRoute: typeof authedKirtanRoute
  authedLeaderboardRoute: typeof authedLeaderboardRoute
  authedProfileRoute: typeof authedProfileRoute
  authedEchoEchoIdRoute: typeof authedEchoEchoIdRoute
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  authedUsernameRoute: authedUsernameRoute,
  authedAccountRoute: authedAccountRoute,
  authedFeedRoute: authedFeedRoute,
  authedKirtanRoute: authedKirtanRoute,
  authedLeaderboardRoute: authedLeaderboardRoute,
  authedProfileRoute: authedProfileRoute,
  authedEchoEchoIdRoute: authedEchoEchoIdRoute,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authedRouteRoute: authedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLeaderboardSubscribeRoute: ApiLeaderboardSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
